name: Construcción y despliegue de una aplicación MVC a Azure

env:
  AZURE_WEBAPP_NAME: upt-awa-451  # Aquí va el nombre de su aplicación en Azure
  DOTNET_VERSION: '8'             # La versión de .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read  # Permiso adicional en caso de que lo necesites

jobs:
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Token personal de acceso

      - name: 'Pull existing Docker image from GHCR'
        run: |
          # Hala la imagen existente desde GHCR (asegúrate de que esté en minúsculas)
          docker pull ghcr.io/salinas-condori-erick/ericku2-app:latest

      - name: Desplegar a Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}  # Nombre de la aplicación en Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Secreto de perfil de publicación
          images: ghcr.io/salinas-condori-erick/ericku2-app:latest  # Nombre de la imagen en minúsculas
