name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Obtiene el historial completo del repo

      - name: List files in workspace  # Verifica la estructura del repo antes de ejecutar Sonar
        run: ls -R

      - name: Install SonarCloud Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Run SonarCloud Scanner
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet sonarscanner begin /k:"salinas-condori-erick_laboratorio2_u2" /o:"salinas-condori-erick" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=${{ secrets.SONAR_TOKEN }}
          dotnet build src/*.csproj  # Detecta automáticamente el archivo .csproj en src/
          dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}

  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        run: |
          pip install semgrep
          semgrep --config=auto --json --output=semgrep-results.json || true

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4  # Actualizado a v4
        with:
          name: semgrep-results
          path: semgrep-results.json
