name: Terraform Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    name: TfSec & Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar TfSec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Ejecutar TfSec
        run: tfsec . --soft-fail

      - name: Instalar Trivy
        run: |
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
          tar -xzf trivy_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Ejecutar Trivy en Terraform
        run: trivy config .
