name: Terraform Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    name: TfSec & Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Instalar TfSec
      - name: Instalar TfSec
        run: |
          curl -fsSL https://aquasecurity.github.io/tfsec/install.sh | bash

      # Ejecutar TfSec en la carpeta del código Terraform
      - name: Ejecutar TfSec
        run: tfsec . --soft-fail

      # Instalar Trivy (Especificamos una versión estable)
      - name: Instalar Trivy
        run: |
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/download/v0.48.0/trivy_0.48.0_Linux-64bit.tar.gz
          tar -xzf trivy_0.48.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      # Ejecutar Trivy para escanear configuraciones Terraform
      - name: Ejecutar Trivy en Terraform
        run: trivy config .
